FROM ubuntu as builder
RUN apt-get update && apt-get install -y git golang make libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
RUN git clone -b v6.29.3 --depth 1 https://github.com/facebook/rocksdb.git /rocksdb && cd /rocksdb &&\
    export CXXFLAGS='-Wno-error=deprecated-copy -Wno-error=pessimizing-move -Wno-error=class-memaccess' &&\
    make static_lib
# docker build -t yesq/rocksdb_builder:v6.29.3 .
