FROM ubuntu as builder
RUN apt-get update && apt-get install -y git golang make libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
RUN git clone -b v6.29.3 --depth 1 https://github.com/facebook/rocksdb.git /rocksdb && cd /rocksdb &&\
    export CXXFLAGS='-Wno-error=deprecated-copy -Wno-error=pessimizing-move -Wno-error=class-memaccess' &&\
    make static_lib
COPY ./go.mod ./go.sum /data/src/
RUN cd /data/src/ && go mod download
# docker build -t onfinality/go-dict:builder .
# PLEASE NOTE this image was build on chip AMD EPYC 7571. Then the binary can run on both Intel and AMD chips.
# Maybe adjust rocksdb compiling parameters could remove AMD chips dependence. This need be confirmed.