name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile_rocksdb_builder'
  pull_request:
    paths:
      - 'Dockerfile_rocksdb_builder'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: onfinality
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./Dockerfile_rocksdb_builder
    #     push: true
    #     tags: onfinality/go-dict:builder
